[package]
name = "git-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-url-parse = "0.4.4"
regex = "1.10.2"
